"""delete posts and comments

Revision ID: 9664e6b1e190
Revises: 5b5a871279de
Create Date: 2018-02-27 20:48:26.300140

"""

# revision identifiers, used by Alembic.
revision = '9664e6b1e190'
down_revision = '5b5a871279de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
